### PR TITLE
Pin Manifests to the Julia Versions Used in Paper and Update README 

### PR DESCRIPTION
**Pull request by lrennels**
This PR should handle #3

In PR #2 Lisa updated the environments to the latest Julia version at that time (v1.9.3) for the replication code. This PR rolls back these Julia versions to match exactly what the code was run with. This is important because while the code is compatible with any version of Julia (at least with the major version 1, so any 1.X version), random number generators have changed between minor versions, such that identical replication of Monte Carlo Simulation results is only possible when matching the Julia version.

We carry this out in two ways:

1. We update the README to document the information, and also instruct users on how to add a given Julia version to their system and run a file using that version.
2. We revert the `Manifest.toml` files back to what they were at the time code was run (commit 7df05b3), which makes sure the Manifest is compatible with the Julia version (different Manifest formats started being used after 1.6) **and** pins to the environment used at the time of code being run.

We could also update the Manifests by re-building them when in the proper Julia version, but we'll try this way for now as it seems the most faithful to the replication goal.

### CODE REVIEW

**Comment by lrennels** [comment]
Here I'm tracking the minimal changes I made from at-runtime Manifests from commit #7df05b3. This is overkill, and looks more complex than it is, but is just helpful to keep track of as I go and in case we have any questions later.

- [bc3e7ea](https://github.com/bryanparthum/schfc-paper/pull/4/commits/bc3e7ea58eb0a1e1cb3441606805dbd762689c10) For MimiGIVE code I updated to use the `main` branch instead of `add-hfs` since before publication we merged that (https://github.com/lrennels/MimiGIVE.jl.git), done with 
```
add https://github.com/lrennels/MimiGIVE.jl
```
which changed
```
 [[MimiGIVE]]
 deps = ["CSVFiles", "DataFrames", "Dates", "DelimitedFiles", "Distributions", "Interpolations", "JSON", "LinearAlgebra", "Mimi", "MimiBRICK", "MimiCIAM", "MimiFAIRv1_6_2", "MimiMooreEtAlAgricultureImpacts", "MimiRFFSPs", "MimiSSPs", "Mimi_NAS_pH", "NetCDF", "PDMats", "Query", "Random", "StatsBase", "XLSX"]
 git-tree-sha1 = "097fee678dce0627d7240825dbb8cfeb081cc475"
 repo-rev = "add-hfcs"
 repo-url = "https://github.com/lrennels/MimiGIVE.jl.git"
 uuid = "08b927d4-7a58-4cf8-85d0-bad32a16dfbc"
 version = "1.0.1-DEV"
```
to
```
[[MimiGIVE]]
 deps = ["CSVFiles", "DataFrames", "Dates", "DelimitedFiles", "Distributions", "Interpolations", "JSON", "LinearAlgebra", "Mimi", "MimiBRICK", "MimiCIAM", "MimiFAIRv1_6_2", "MimiMooreEtAlAgricultureImpacts", "MimiRFFSPs", "MimiSSPs", "Mimi_NAS_pH", "NetCDF", "PDMats", "Query", "Random", "StatsBase", "XLSX"]
 git-tree-sha1 = "10f271f64b753a2c2b74d344dec9efda10720d4d"
 repo-rev = "main"
 repo-url = "https://github.com/lrennels/MimiGIVE.jl.git"
 uuid = "08b927d4-7a58-4cf8-85d0-bad32a16dfbc"
 version = "1.0.1-DEV"
```
alongside a few small helper package updates.

- [b198180](https://github.com/bryanparthum/schfc-paper/pull/4/commits/b19818089c0fe8f43bcc29116b801bde8f88c492) For MimiIWG_FAIRv162 code use the online GitHub repo instead of lrennels local copy, done with 
```
add https://github.com/lrennels/MimiIWG_FAIRv162
```
which changed
```
[[deps.MimiIWG_FAIRv162]]
deps = ["Arrow", "CSVFiles", "DataFrames", "Dates", "DelimitedFiles", "Distributions", "Interpolations", "Mimi", "MimiDICE2010", "MimiFUND", "MimiPAGE2009", "Query", "Statistics", "StatsBase", "XLSX"]
path = "/Users/lisarennels/.julia/dev/MimiIWG_FAIRv162"
uuid = "bf4e0101-1676-44a8-91f1-dae5ac8d85ac"
version = "0.1.0-DEV"
```
to
```
[[deps.MimiIWG_FAIRv162]]
deps = ["Arrow", "CSVFiles", "DataDeps", "DataFrames", "Dates", "DelimitedFiles", "Distributions", "Interpolations", "Mimi", "MimiDICE2010", "MimiFUND", "MimiPAGE2009", "Query", "Statistics", "StatsBase", "XLSX"]
git-tree-sha1 = "4407297cb813b1ae7430197e0cbcb61efea305a6"
repo-rev = "main"
repo-url = "https://github.com/lrennels/MimiIWG_FAIRv162"
uuid = "4ed45b26-778f-11ee-1a7e-43a2532b2fa8"
version = "0.1.0-DEV"
```
alongside a few small helper package updates.

**Comment by bryanparthum** [comment]
this all sounds good. Thanks so much for the careful tracking @lrennels. Should we go ahead an pull and close?

**Comment by lrennels** [comment]
Yep I think you're good to go! And then just ping me if it doesn't do what we think it should :)

**Comment by lrennels** [comment]
Oh yea @bryanparthum sorry for changing the number of processors -- feel free to change back -- my laptop was being rude

**Comment by bryanparthum** [comment]
> Oh yea @bryanparthum sorry for changing the number of processors -- feel free to change back -- my laptop was being rude

ha no it is a good idea. I just added some documentation so the user can choose accordingly and wisely.

**Pull request merged**
